# Generated by Django 6.0.2 on 2026-02-27 21:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('category', models.CharField(choices=[('Billing', 'Billing'), ('Refund', 'Refund'), ('Account Access', 'Account Access'), ('Cancellation', 'Cancellation'), ('General Inquiry', 'General Inquiry')], db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('response_time_ms', models.IntegerField(help_text='Response time in milliseconds')),
            ],
            options={
                'verbose_name': 'Trace',
                'verbose_name_plural': 'Traces',
                'ordering': ['-timestamp'],
            },
        ),
    ]
