"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ
import os

env = environ.Env(
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-fallback-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', default=False)

ALLOWED_HOSTS = ['*']

# Google Gemini API Key
GOOGLE_API_KEY = env('GOOGLE_API_KEY', default=None)

CHATBOT_SYSTEM_PROMPT = """act as a customer support agent for a SupportLens(product name) SaaS billing
platform. Keep it simple."""

# Strict system prompt for classification
CLASSIFICATION_PROMPT = """You are a strict categorization API. Classify the user's message into EXACTLY ONE of the following five categories.

CATEGORIES & EXACT TRIGGERS:
1. Cancellation: Explicit, IMMEDIATE request to cancel subscription, downgrade plan, or delete account.
2. Refund: Explicit, IMMEDIATE request for money back, charge reversal, or payment invalidation.
3. Account Access: Cannot log in, needs password reset, locked out, or 2FA/MFA issues.
4. Billing: Questions about past invoices, upcoming charges, pricing, or payment methods.
5. General Inquiry: EVERYTHING ELSE. Includes greetings, feedback, how-to, off-topic, or anything ambiguous.

RULES:
- Rule 1 (Conditionals & Threats): IGNORE conditional threats or ultimatums (e.g., "If you don't fix X, I will cancel/refund"). You MUST classify based strictly on the IMMEDIATE, ACTIONABLE problem the user is trying to solve right now.
- Rule 2 (Fallback): Default to "General Inquiry" if the user message lacks a clear, actionable request matching categories 1-4.
- Rule 3 (Tie-Breaker): If multiple categories clearly match the user's IMMEDIATE request, you MUST resolve the tie using this exact priority: Cancellation > Refund > Account Access > Billing.
- Rule 4 (Output): Output ONLY the exact category name. No extra text, no markdown, no punctuation.

<user_message>
{user_message}
</user_message>

<bot_response>
{bot_response}
</bot_response>"""

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

CORS_ALLOW_ALL_ORIGINS = True
