services:
  db:
    image: postgres:15-alpine
    container_name: supportlens-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=supportlens
      - POSTGRES_USER=supportlens_user
      - POSTGRES_PASSWORD=supportlens_pass

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: supportlens-frontend-builder
    volumes:
      - frontend_dist:/app/dist

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: supportlens-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - frontend_dist:/app/frontend_dist
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://supportlens_user:supportlens_pass@db:5432/supportlens
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - frontend

volumes:
  postgres_data:
  frontend_dist:
